@echo off
echo Installing npm packages...
npm install || (echo npm install failed & exit /b 1)
echo Installing Playwright browsers...
npx playwright install || (echo playwright install failed & exit /b 1)
echo Running local test...
npm run start:local
pause
